[package]
name = "vertex_lang"
version = "0.1.0"
edition = "2021"
authors = ["TheDudeFromCI <thedudefromci@gmail.com>"]
description = "The compiler and interprter for the Vertex programming language."
homepage = "https://github.com/TheDudeFromCI/VertexLang"
repository = "https://github.com/TheDudeFromCI/VertexLang"
license = "MIT"
keywords = ["vertex", "language", "programming", "compiler"]
readme = "README.md"
exclude = [".github/*"]

[dependencies]
regex = "1"
enum-map = "0.6.4"
strum = "0.23"
strum_macros = "0.23"
readonly = "0.2"
