name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Rustup
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup-init.sh

    - name: Print Buildtool Versions
      run: |
        rustc -Vv
        cargo -V

    - name: Build Project
      run: cargo build

    - name: Run Unit Tests
      run: cargo test

    - name: Verify Formatting
      run: cargo fmt --all -- --check

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rustup
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup-init.sh

      - name: Print Buildtool Versions
        run: |
          rustc -Vv
          cargo -V

      - name: Build
        run: cargo build --release

      - name: Deploy
        run: cargo publish
