name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy

    - name: Print Buildtool Versions
      run: |
        rustc -Vv
        cargo -V

    - name: Build Project
      run: cargo build
      env:
        RUSTFLAGS: -D warnings

    - name: Run Unit Tests
      run: |
        cargo test --all-targets
        cargo test --doc

    - name: Verify Formatting
      run: cargo +nightly fmt --all -- --check

    - name: Verify Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install latest
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Print Buildtool Versions
        run: |
          rustc -Vv
          cargo -V

      - name: Build
        run: cargo build --release

      - name: Deploy
        run: cargo publish
